version: "2"
services:
  node:
    image: "node:current-alpine3.20"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "1234:3000"
    command: /bin/sh -c "npm install && npm start"
